### PR TITLE
Fixing is_main initialization in create_domain.

### LINKED ISSUE #15: Segmentation fault with reagent queues
The example is `queue_test.ml` under ocaml-reagents [1]. The segfault can be replicated by:

    git clone https://github.com/kayceesrk/ocaml-reagent.git
    cd ocaml-reagent
    git checkout mc-sched-segfault
    make
    ./queue_test.byte 8 100000

Running under debug mode leads to a variety of error conditions. It either (1) gets stuck with the following output:

    [01] Handling read fault for domain [01]
    [04] Read fault returned (0x1022bd260)
    [01] Read fault to domain [04]
    [04] Handling read fault for domain [04]
    [01] Read fault returned (0x10228cc70)
    [05] Major slice: 226046 alloc, 1186741 work, 12289 sweep, 89140 mark (29708 blocks)
    [05] Slow spin-wait loop in stw_phase at domain.c:436
    [04] Slow spin-wait loop in stw_phase at domain.c:436
    [07] Slow spin-wait loop in stw_phase at domain.c:436

or terminates just after starting a major slice collection (2):

    [02] Major slice: 262143 alloc, 1376250 work, 0 sweep, 417685 mark (139228 blocks)
    [03] Contributing 255 heaps to GC
    [02] Contributing 1 heaps to GC
    [03] GCing inactive domain [00]
    [03] Pooled memory: 331776 alloced, 93674 free, 359 fragmentation
    [03] Large memory: 4958 alloced, 0 free, 8 fragmentation
    [02] Pooled memory: 1978368 alloced, 12907 free, 483 fragmentation
    [02] Large memory: 4099 alloced, 0 free, 2 fragmentation
    file major_gc.c; line 114 ### Assertion failed: v == mark_normalise(v)
    Abort trap: 6

or terminates with (3):

    [04] Major slice: 262143 alloc, 1376250 work, 16385 sweep, 1074197 mark (358060 blocks)
    [05] Read fault returned (0x10da8f430)
    [05] Contributing 251 heaps to GC
    [04] Contributing 1 heaps to GC
    [03] Contributing 1 heaps to GC
    [01] Contributing 3 heaps to GC
    [01] GCing inactive domain [00]
    [01] Pooled memory: 155648 alloced, 93995 free, 316 fragmentation
    [01] Large memory: 4958 alloced, 0 free, 8 fragmentation
    [03] Pooled memory: 163840 alloced, 27669 free, 40 fragmentation
    [03] Large memory: 4099 alloced, 0 free, 2 fragmentation
    [03] Minor collection starting
    [03] Minor collection completed: 0 of 840 kb live, 0 pointers rewritten
    [05] Pooled memory: 290816 alloced, 33798 free, 71 fragmentation
    [05] Large memory: 4099 alloced, 0 free, 2 fragmentation
    [05] Minor collection starting
    [05] Minor collection completed: 0 of 1474 kb live, 0 pointers rewritten
    [04] Pooled memory: 1392640 alloced, 15675 free, 340 fragmentation
    [04] Large memory: 4099 alloced, 0 free, 2 fragmentation
    [04] Finished marking major heap. Marked 445442 blocks
    [03] Finished marking major heap. Marked 153160 blocks
    Segmentation fault: 11

or (4):

    [05] Minor collection starting
    [06] Finished marking major heap. Marked 2736 blocks
    [00] Large memory: 4958 alloced, 0 free, 8 fragmentation
    [05] Minor collection completed: 0 of 76 kb live, 0 pointers rewritten
    [06] GCing inactive domain [07]
    [00] Minor collection starting
    [06] Pooled memory: 32768 alloced, 10489 free, 8 fragmentation
    [05] Finished marking major heap. Marked 4756 blocks
    [06] Large memory: 4099 alloced, 0 free, 2 fragmentation
    [01] Finished marking major heap. Marked 27399 blocks
    [06] Finished marking major heap. Marked 48626 blocks
    [00] Minor collection completed: 1472 of 1922 kb live, 0 pointers rewritten
    file shared_heap.c; line 371 ### Assertion failed: h && !Has_status_hd(h, global.GARBAGE)
    Abort trap: 6

The debug logs point to error introduced by allocation/manipulation of the major heap that is triggered during major collection. 

[1] https://github.com/kayceesrk/ocaml-reagent/blob/mc-sched-segfault/test/queue_test.ml

### PR DESCRIPTION
**Pull request by kayceesrk**
Since the `is_main` field was always 0, lock on `pool_freelist` was used without being uninitialized [1] leading to mutual exclusion failures. This was the cause of strange behaviors with pools such as cycles, and the source of segfaults in #15. This in combination with the PR #18 fixes #15.

This PR additionally sets the owner of released pools to be NULL in order to better track ownership.

[1] https://github.com/ocamllabs/ocaml-multicore/blob/821b653592ddca80278e82903100deeb5934b6c2/byterun/shared_heap.c#L84

### CODE REVIEW

File: byterun/domain.c [hunk 1]
```diff
@@ -148,7 +148,7 @@ static void create_domain(uintnat initial_minor_heap_size, int is_main) {
 
   if (d) {
     d->running = 1;
-    d->state.is_main = 0;
+    d->state.is_main = is_main;
```
Comment (stedolan) [inline byterun/domain.c]: **facepalm**

Well found :)

**Comment by stedolan** [comment]
Nice!
